### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by fredRos** [eos/eos#411]
I followed the installation instructions at https://eos.github.io/doc/installation.html#installation-with-pip3 and then got errors. I am looking into fixing that myself but I want to post them here in case somebody else has the issue and comes here from a search engine

```console
at 20:18:09 ❯ pip3 install --user eoshep
Collecting eoshep
  Downloading eoshep-0.3.3-cp38-cp38-manylinux2014_x86_64.whl (44.3 MB)
     |████████████████████████████████| 44.3 MB 641 kB/s 
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from eoshep) (5.3.1)
Requirement already satisfied: numpy<2,>=1.13 in /usr/lib/python3/dist-packages (from eoshep) (1.17.4)
Requirement already satisfied: pypmc>=1.1.4 in /home/fred/.local/lib/python3.8/site-packages (from eoshep) (1.1.4)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from eoshep) (3.1.2)
Collecting h5py
  Downloading h5py-3.5.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 200 kB/s 
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from eoshep) (1.3.3)
ERROR: h5py 3.5.0 has requirement numpy>=1.17.5; python_version == "3.8", but you'll have numpy 1.17.4 which is incompatible.
Installing collected packages: h5py, eoshep
Successfully installed eoshep-0.3.3 h5py-3.5.0
```

So it says it successfully installed but there was an error: why does it continue past h5py?

```
ERROR: h5py 3.5.0 has requirement numpy>=1.17.5; python_version == "3.8", but you'll have numpy 1.17.4 which is incompatible.
```

Then `import eos` fails:

```
at 20:30:31 ❯ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fred/.local/lib/python3.8/site-packages/eos/__init__.py", line 30, in <module>
    from .data import *
  File "/home/fred/.local/lib/python3.8/site-packages/eos/data/__init__.py", line 20, in <module>
    from .pypmc import *
  File "/home/fred/.local/lib/python3.8/site-packages/eos/data/pypmc.py", line 19, in <module>
    import pypmc
  File "/home/fred/.local/lib/python3.8/site-packages/pypmc/__init__.py", line 9, in <module>
    from . import mix_adapt, density, sampler, tools
  File "/home/fred/.local/lib/python3.8/site-packages/pypmc/mix_adapt/__init__.py", line 7, in <module>
    from . import hierarchical, variational, pmc, r_value
  File "pypmc/mix_adapt/variational.pyx", line 1, in init pypmc.mix_adapt.variational
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

I'm not even sure the two errors are related because I installed `pypmc` locally.

**Comment by fredRos** [comment]
I removed `pypmc` and eos, then reinstalled, still got the same error. This is in 

```
Linux ThinkPad-E495 5.11.0-36-generic #40~20.04.1-Ubuntu SMP Sat Sep 18 02:14:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

and I'm not using venv, or conda.

```
at 20:39:34 ❯ pip3 install --user eoshep
Collecting eoshep
  Using cached eoshep-0.3.3-cp38-cp38-manylinux2014_x86_64.whl (44.3 MB)
Requirement already satisfied: numpy<2,>=1.13 in /usr/lib/python3/dist-packages (from eoshep) (1.17.4)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from eoshep) (3.1.2)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from eoshep) (5.3.1)
Collecting pypmc>=1.1.4
  Downloading pypmc-1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 1.5 MB/s 
Requirement already satisfied: h5py in /home/fred/.local/lib/python3.8/site-packages (from eoshep) (3.5.0)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from eoshep) (1.3.3)
Installing collected packages: pypmc, eoshep
Successfully installed eoshep-0.3.3 pypmc-1.2

at 20:39:58 ❯ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eos
...
  File "pypmc/mix_adapt/variational.pyx", line 1, in init pypmc.mix_adapt.variational
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

```

**Comment by dvandyk** [comment]
Honestly, this is not an EOS problem. ``pip`` simply is not a package manager. (I have other words for it!)

I think what is happening here is that
 1.  your ``pypmc`` was built against some ``numpy`` version
 2. ``h5py`` requires an up-to-date ``numpy`` version;
 3. ``pip`` does not update installed packages, even when more recent versions are needed.
 
 Can you try to carry out these steps please?
  - ``pip3 install --user --upgrade eoshep``   (this should upgrade all dependencies of ``eoshep`` as well AFAIK);
  - reinstall ``pypmc``, which probably needs to build against the updated ``numpy``.

**Comment by fredRos** [comment]
@dvandyk No, the mismatch is from the version installed with eos, so I suspect there is some issue in how the pypmc binary is built for the release on pypi

I made sure there is no pypmc:

```
at 20:58:34 ❯ pip3 uninstall pypmc
at 20:59:28 ❯ python3 -c "import pypmc"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pypmc'
```

good, then remove and install eos

```
at 21:02:44 ❯ python3 -c "import eos"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'eos'

at 21:03:09 ❯ pip3 install --user eoshep
Collecting eoshep
  Using cached eoshep-0.3.3-cp38-cp38-manylinux2014_x86_64.whl (44.3 MB)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from eoshep) (5.3.1)
Requirement already satisfied: h5py in /home/fred/.local/lib/python3.8/site-packages (from eoshep) (3.5.0)
Requirement already satisfied: numpy<2,>=1.13 in /usr/lib/python3/dist-packages (from eoshep) (1.17.4)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from eoshep) (1.3.3)
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from eoshep) (3.1.2)
Collecting pypmc>=1.1.4
  Using cached pypmc-1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
Installing collected packages: pypmc, eoshep
Successfully installed eoshep-0.3.3 pypmc-1.2
```
and the error is still there

```
at 21:03:32 ❯ python3 -c "import eos"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fred/.local/lib/python3.8/site-packages/eos/__init__.py", line 30, in <module>
    from .data import *
  File "/home/fred/.local/lib/python3.8/site-packages/eos/data/__init__.py", line 20, in <module>
    from .pypmc import *
  File "/home/fred/.local/lib/python3.8/site-packages/eos/data/pypmc.py", line 19, in <module>
    import pypmc
  File "/home/fred/.local/lib/python3.8/site-packages/pypmc/__init__.py", line 9, in <module>
    from . import mix_adapt, density, sampler, tools
  File "/home/fred/.local/lib/python3.8/site-packages/pypmc/mix_adapt/__init__.py", line 7, in <module>
    from . import hierarchical, variational, pmc, r_value
  File "pypmc/mix_adapt/variational.pyx", line 1, in init pypmc.mix_adapt.variational
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by fredRos** [comment]
the upgrade does nothing and the error persists

```
at 21:05:57 ❯ pip3 install --user --upgrade eoshep
Requirement already up-to-date: eoshep in /home/fred/.local/lib/python3.8/site-packages (0.3.3)
Requirement already satisfied, skipping upgrade: pypmc>=1.1.4 in /home/fred/.local/lib/python3.8/site-packages (from eoshep) (1.2)
Requirement already satisfied, skipping upgrade: h5py in /home/fred/.local/lib/python3.8/site-packages (from eoshep) (3.5.0)
Requirement already satisfied, skipping upgrade: scipy in /usr/lib/python3/dist-packages (from eoshep) (1.3.3)
Requirement already satisfied, skipping upgrade: matplotlib in /usr/lib/python3/dist-packages (from eoshep) (3.1.2)
Requirement already satisfied, skipping upgrade: numpy<2,>=1.13 in /usr/lib/python3/dist-packages (from eoshep) (1.17.4)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/lib/python3/dist-packages (from eoshep) (5.3.1)
```

**Comment by fredRos** [comment]
But for me it works if I build pypmc manually, then the numpy version mismatch is avoided

```
at 21:06:10 ❯ git clone git@github.com:pypmc/pypmc.git

at 21:07:07 ❯ cd pypmc/ && make install3

at 21:08:27 ❯ python3 -c "import eos"
# no error on import
```

**Comment by fredRos** [comment]
I'm closing this issue as there is a workaround. If more people run into this issue, we may have to look into a better solution with the pypi binaries @dvandyk
