### ISSUE TITLE
Test installation with conda/virtualenv

### ISSUE THREAD

**Issue by fredRos** [eos/eos#48]

**Comment by fredRos** [comment]
Issues with python2 vs python3. On my ubuntu 16.04 machine I have both. eos prefers python3 but the system default is python2. Leads to this error 

```
os-plot
Traceback (most recent call last):
  File "/home/beaujean/.local/sw/eos/linux-ubuntu-16.04-x86_64/master/bin/eos-plot", line 20, in <module>
    import eos
  File "/home/beaujean/.local/sw/eos/linux-ubuntu-16.04-x86_64/master/lib/python3.5/site-packages/eos.py", line 16, in <module>
    from _eos import _Parameters
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0: undefined symbol: PyUnicode_AsUTF8String
```

Fix it with 

    python3 `which eos-plot`

**Comment by dvandyk** [comment]
EOS is regularly used with Python2/3 dual installations and with virtualenv. Closing this issue.
